#from ArvoreBinariaBusca import ArvoreBinaria, No
from BinarySearchTree import BinarySearchTree, Node
from Carro import Carro

arv = BinarySearchTree()
arv.add(Carro(123,'Fusca',1970))
arv.add(Carro(456,'Celta', 2002))
arv.add(Carro(777,'Kwid', 2020))
arv.add(Carro(888,'Opala', 1991))
arv.add(Carro(999,'Nissan Kicks', 2023))
arv.add(Carro(174,'Audi Eletrico ultima geracao', 2023))
print('Root: ', arv.getRoot())
print('Len: ', len(arv))
print('Imprimindo em preordem() a arvore completa')
arv.preorder()
chave = Carro(568,'', 0)
print('Busca: ', arv.search(chave))
exit()
print('\nRemove "G"')
arv.deleteNode('G')
arv.preorder()
print('\nRemove "F"')
arv.deleteNode('F')
arv.preorder()
print('\nRemove "H"')
arv.deleteNode('H')
arv.preorder()
print('Root: ', arv.getRoot())
print('\nRemove "A"')
arv.deleteNode('A')
arv.preorder()
print('Root: ', arv.getRoot())
print('\nRemove "D"')
arv.deleteNode('D')
arv.preorder()
print('\nRemove "F"')
arv.deleteNode('F')
arv.preorder()
print('Root: ', arv.getRoot())
print('\nRemove "M"')
arv.deleteNode('M')
arv.preorder()
print('\nRemove "K"')
arv.deleteNode('K')
arv.preorder()
print('Root: ', arv.getRoot())
print('\nLen: ', len(arv))

# print('Remove "A"')
# arv.removeNo('A')
# arv.preordem()

# print('\nBusca "H":', arv.busca('H'))

